/**
 * Lifecycle Gate — Enforcement and Auto-Repair for Bound Tasks
 *
 * This gate ensures that all MCP-bound tasks follow the strict lifecycle:
 * 1. Task fetched via MCP read tool → bound
 * 2. update_task_plan → plan written
 * 3. set_task_status(in_progress) → status updated
 * 4. [LLM does the actual work]
 * 5. update_task_walkthrough → walkthrough written
 * 6. set_task_status(in_review) → status updated, lifecycle complete
 *
 * The gate is called BEFORE allowing the LLM to continue.
 * If lifecycle steps are missing, it auto-repairs by calling the appropriate tools.
 */

import { bindingTracker } from './binding-tracker.js';
import {
	type AutoRepairResult,
	type LifecycleViolation,
	LifecycleStep,
	isEnforcementActive
} from './lifecycle-config.js';
import { getApiClient } from '@lib/api.js';
import { requireProject } from '@lib/config.js';
import { getGitMetadata } from '@lib/git.js';
import { stableHash } from '@lib/observability.js';
import { buildSuggestedGitCommit } from '@lib/walkthrough-commit.js';

// ─── Fallback Artifacts ──────────────────────────────────────────────────────

interface FallbackPlan {
	summary: string;
	steps: string[];
	files_affected: string[];
}

interface FallbackWalkthrough {
	summary: string;
	changes: string[];
	files_modified: string[];
}

function _buildFallbackPlan(_taskId: string): FallbackPlan {
	return {
		summary: 'Plan auto-generated by lifecycle enforcement',
		steps: ['[See task description for implementation details]'],
		files_affected: []
	};
}

function _buildFallbackWalkthrough(_taskId: string): FallbackWalkthrough {
	return {
		summary: 'Implementation completed. Walkthrough auto-generated by lifecycle enforcement.',
		changes: ['[See implementation details]'],
		files_modified: []
	};
}

// ─── Lifecycle Gate ──────────────────────────────────────────────────────────

/**
 * The Lifecycle Gate enforces write tool usage for bound tasks.
 *
 * Usage:
 * ```typescript
 * import { lifecycleGate } from './lifecycle/lifecycle-gate.js';
 *
 * // Before allowing LLM to continue (e.g., after generating code)
 * const result = await lifecycleGate.enforceBeforeContinue();
 * if (result.enforced) {
 *   console.log(`Auto-repaired: ${result.step}`);
 * }
 * ```
 */
export class LifecycleGate {
	/**
	 * Check and enforce lifecycle for the current bound task.
	 *
	 * This should be called:
	 * - Before the LLM generates code (to ensure plan is written)
	 * - When the LLM signals completion (to ensure walkthrough is written)
	 *
	 * @param taskId - Optional. If not provided, uses the current bound task.
	 * @returns AutoRepairResult indicating what happened.
	 */
	async enforceBeforeContinue(taskId?: string): Promise<AutoRepairResult> {
		// Check if enforcement is active
		if (!isEnforcementActive()) {
			return { enforced: false, reason: 'not_bound' };
		}

		// Resolve taskId
		const targetTaskId = taskId ?? bindingTracker.getCurrentTaskId();
		if (!targetTaskId) {
			return { enforced: false, reason: 'not_bound' };
		}

		// Check if task is bound
		if (!bindingTracker.isBound(targetTaskId)) {
			return { enforced: false, reason: 'not_bound' };
		}

		const boundTask = bindingTracker.getBoundTask(targetTaskId);
		if (!boundTask) {
			return { enforced: false, reason: 'not_bound' };
		}

		const state = bindingTracker.getState(targetTaskId);
		if (!state) {
			return { enforced: false, reason: 'not_bound' };
		}

		// STEP 1: Check if plan needs to be written
		// This is the most critical step — plan must exist before work starts
		if (!state.planWrittenAt) {
			console.log(`[LifecycleGate] Auto-repairing: plan for task ${targetTaskId}`);

			const fallbackPlan = _buildFallbackPlan(targetTaskId);

			try {
				await this.writePlan(targetTaskId, fallbackPlan);
				bindingTracker.markPlanWritten(targetTaskId);

				// Also set in_progress if not already
				if (!state.inProgressAt) {
					await this.setStatus(targetTaskId, 'in_progress');
					bindingTracker.markInProgress(targetTaskId);
				}

				return {
					enforced: true,
					step: LifecycleStep.PLAN,
					reason: 'auto_repaired',
					action: 'plan_written'
				};
			} catch (error) {
				console.error(`[LifecycleGate] Failed to auto-repair plan:`, error);
				return {
					enforced: false,
					reason: 'not_bound'
				};
			}
		}

		// STEP 2: Check if in_progress status needs to be set
		// This should have been set when plan was written
		if (!state.inProgressAt && state.planWrittenAt) {
			console.log(`[LifecycleGate] Auto-repairing: in_progress status for task ${targetTaskId}`);

			try {
				await this.setStatus(targetTaskId, 'in_progress');
				bindingTracker.markInProgress(targetTaskId);

				return {
					enforced: true,
					step: LifecycleStep.IN_PROGRESS,
					reason: 'auto_repaired',
					action: 'status_updated'
				};
			} catch (error) {
				console.error(`[LifecycleGate] Failed to auto-repair in_progress:`, error);
				return {
					enforced: false,
					reason: 'not_bound'
				};
			}
		}

		// STEP 3: Check if walkthrough needs to be written
		// This is checked when the LLM signals completion
		if (state.inProgressAt && !state.walkthroughWrittenAt) {
			console.log(`[LifecycleGate] Auto-repairing: walkthrough for task ${targetTaskId}`);

			const fallbackWalkthrough = _buildFallbackWalkthrough(targetTaskId);

			try {
				await this.writeWalkthrough(targetTaskId, fallbackWalkthrough);
				bindingTracker.markWalkthroughWritten(targetTaskId);

				// Also set in_review if not already
				if (!state.inReviewAt) {
					await this.setStatus(targetTaskId, 'in_review');
					bindingTracker.markInReview(targetTaskId);
				}

				return {
					enforced: true,
					step: LifecycleStep.WALKTHROUGH,
					reason: 'auto_repaired',
					action: 'walkthrough_written'
				};
			} catch (error) {
				console.error(`[LifecycleGate] Failed to auto-repair walkthrough:`, error);
				return {
					enforced: false,
					reason: 'not_bound'
				};
			}
		}

		// STEP 4: Check if in_review status needs to be set
		// This should have been set when walkthrough was written
		if (state.walkthroughWrittenAt && !state.inReviewAt) {
			console.log(`[LifecycleGate] Auto-repairing: in_review status for task ${targetTaskId}`);

			try {
				await this.setStatus(targetTaskId, 'in_review');
				bindingTracker.markInReview(targetTaskId);

				return {
					enforced: true,
					step: LifecycleStep.IN_REVIEW,
					reason: 'auto_repaired',
					action: 'status_updated'
				};
			} catch (error) {
				console.error(`[LifecycleGate] Failed to auto-repair in_review:`, error);
				return {
					enforced: false,
					reason: 'not_bound'
				};
			}
		}

		// All steps complete
		return {
			enforced: false,
			reason: 'lifecycle_complete'
		};
	}

	/**
	 * Mark that the plan step has been completed (called after update_task_plan).
	 */
	markPlanWritten(taskId: string): void {
		bindingTracker.markPlanWritten(taskId);
	}

	/**
	 * Mark that the walkthrough step has been completed (called after update_task_walkthrough).
	 */
	markWalkthroughWritten(taskId: string): void {
		bindingTracker.markWalkthroughWritten(taskId);
	}

	/**
	 * Check if a lifecycle violation would occur for a given tool call.
	 * Returns the violation details if invalid, null if valid.
	 */
	checkViolation(tool: string, taskId: string): LifecycleViolation | null {
		if (!isEnforcementActive()) {
			return null;
		}

		if (!bindingTracker.isBound(taskId)) {
			// Not bound — no violation
			return null;
		}

		const state = bindingTracker.getState(taskId);
		if (!state) {
			return null;
		}

		const currentStep = bindingTracker.getCurrentStep(taskId);

		// Rule: set_task_status(in_progress) requires plan
		if (tool === 'set_task_status') {
			if (!state.planWrittenAt) {
				return {
					code: 'LIFECYCLE_VIOLATION',
					reason: 'plan_missing',
					message: 'Cannot set status to in_progress without a persisted plan. Call update_task_plan first.',
					required_tool: 'update_task_plan',
					...(currentStep ? { current_step: currentStep } : {})
				};
			}
		}

		// Rule: set_task_status(in_review) requires walkthrough
		if (tool === 'set_task_status') {
			// Note: we can't know the target status here, so this is handled in enforceBeforeContinue
		}

		return null;
	}

	/**
	 * Get a user-friendly message for auto-repair notifications.
	 */
	getAutoRepairMessage(result: AutoRepairResult): string | null {
		if (!result.enforced) {
			return null;
		}

		switch (result.action) {
			case 'plan_written':
				return `Lifecycle auto-repair: Plan was auto-written because you did not call \`update_task_plan\`. This has been recorded in Fenkit.`;
			case 'walkthrough_written':
				return `Lifecycle auto-repair: Walkthrough was auto-written because you did not call \`update_task_walkthrough\`. This has been recorded in Fenkit.`;
			case 'status_updated':
				return `Lifecycle auto-repair: Task status was auto-updated because the previous step was not properly recorded.`;
			default:
				return `Lifecycle auto-repair was executed. Please continue with your work.`;
		}
	}

	// ─── Private API Helpers ─────────────────────────────────────────────────

	private async writePlan(taskId: string, plan: FallbackPlan): Promise<void> {
		const config = requireProject();
		const api = getApiClient();

		const payloadHash = stableHash({ plan, mode: 'mini' });
		const gitContext = await getGitMetadata();

		// Build the MCP payload (simplified for auto-repair)
		const mcpContext = {
			actor: 'lifecycle-gate',
			tool: 'update_task_plan',
			git_branch: gitContext?.branch ?? null,
			git_commit_hash: gitContext?.commitHash ?? null,
			last_model: 'auto-repair',
			last_seen_at: new Date().toISOString()
		};

		const mcpEvent = {
			tool: 'update_task_plan',
			operation_id: `auto:update_task_plan:${Date.now()}`,
			payload_hash: payloadHash,
			agent: 'lifecycle-gate',
			model: 'auto-repair'
		};

		// Render plan as markdown
		const planContent = this.renderPlanMarkdown(plan);

		// Send to backend
		await api.patch(`/projects/${config.currentProjectId}/tasks/${taskId}`, {
			plan: planContent,
			status: 'in_progress',
			mcpContext,
			mcpEvent
		});
	}

	private async writeWalkthrough(taskId: string, walkthrough: FallbackWalkthrough): Promise<void> {
		const config = requireProject();
		const api = getApiClient();

		const payloadHash = stableHash({ walkthrough, mode: 'mini' });
		const gitContext = await getGitMetadata();

		// Build the MCP payload (simplified for auto-repair)
		const mcpContext = {
			actor: 'lifecycle-gate',
			tool: 'update_task_walkthrough',
			git_branch: gitContext?.branch ?? null,
			git_commit_hash: gitContext?.commitHash ?? null,
			last_model: 'auto-repair'
		};

		const mcpEvent = {
			tool: 'update_task_walkthrough',
			operation_id: `auto:update_task_walkthrough:${Date.now()}`,
			payload_hash: payloadHash,
			agent: 'lifecycle-gate',
			model: 'auto-repair'
		};

		// Render walkthrough as markdown
		const walkthroughContent = this.renderWalkthroughMarkdown(taskId, walkthrough);

		// Send to backend
		await api.patch(`/projects/${config.currentProjectId}/tasks/${taskId}`, {
			walkthrough: walkthroughContent,
			status: 'in_review',
			mcpContext,
			mcpEvent
		});
	}

	private async setStatus(taskId: string, status: string): Promise<void> {
		const config = requireProject();
		const api = getApiClient();

		const payloadHash = stableHash({ status });

		// Build the MCP payload (simplified for auto-repair)
		const mcpContext = {
			actor: 'lifecycle-gate',
			tool: 'set_task_status',
			last_model: 'auto-repair'
		};

		const mcpEvent = {
			tool: 'set_task_status',
			operation_id: `auto:set_task_status:${Date.now()}`,
			payload_hash: payloadHash,
			agent: 'lifecycle-gate',
			model: 'auto-repair'
		};

		// Send to backend
		await api.patch(`/projects/${config.currentProjectId}/tasks/${taskId}`, {
			status,
			mcpContext,
			mcpEvent
		});
	}

	private renderPlanMarkdown(plan: FallbackPlan): string {
		const lines: string[] = [];
		lines.push('## Summary');
		lines.push(plan.summary);
		lines.push('');
		lines.push('## Steps');
		for (const step of plan.steps) {
			lines.push(`- ${step}`);
		}
		lines.push('');
		lines.push('## Files Affected');
		for (const file of plan.files_affected) {
			lines.push(`- \`${file}\``);
		}
		return lines.join('\n').trim();
	}

	private renderWalkthroughMarkdown(taskId: string, walkthrough: FallbackWalkthrough): string {
		const lines: string[] = [];
		lines.push('## Summary');
		lines.push(walkthrough.summary);
		lines.push('');
		lines.push('## Changes');
		for (const change of walkthrough.changes) {
			lines.push(`- ${change}`);
		}
		lines.push('');
		lines.push('## Files Modified');
		for (const file of walkthrough.files_modified) {
			lines.push(`- \`${file}\``);
		}
		lines.push('');

		const suggestedCommit = buildSuggestedGitCommit({
			taskId,
			summary: walkthrough.summary,
			changes: walkthrough.changes,
			filesModified: walkthrough.files_modified
		});
		lines.push('## Suggested Git Commit');
		lines.push(`\`${suggestedCommit}\``);
		return lines.join('\n').trim();
	}
}

/**
 * Singleton instance of LifecycleGate.
 */
export const lifecycleGate = new LifecycleGate();
